# Generated by Django 2.0.5 on 2018-05-13 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3000)),
                ('cantidadEjecuciones', models.PositiveSmallIntegerField()),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(max_length=35)),
                ('nombre2', models.CharField(max_length=35)),
                ('apellido1', models.CharField(max_length=35)),
                ('apellido2', models.CharField(max_length=35)),
                ('edad', models.CharField(max_length=4)),
                ('ciudad', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=35)),
                ('telefono', models.CharField(max_length=35)),
                ('idlenguaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.Lenguaje')),
                ('idpais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.Pais')),
            ],
        ),
        migrations.AddField(
            model_name='codigo',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.Usuario'),
        ),
    ]
