# Generated by Django 2.0.5 on 2018-05-14 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionUsuarios', '0002_auto_20180514_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='idUsuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GestionUsuarios.Usuario'),
        ),
    ]
