# Generated by Django 2.0.5 on 2018-05-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('cantidadEjecuciones', models.PositiveSmallIntegerField()),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('idUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Usuario')),
            ],
        ),
    ]
