# Generated by Django 2.0.5 on 2018-05-29 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PerfilUsuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=35)),
                ('docfile', models.CharField(max_length=100)),
                ('cantidadEjecuciones', models.IntegerField(default=0)),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PerfilUsuario.PerfilUsuario')),
            ],
        ),
    ]
