# Generated by Django 2.0.5 on 2018-05-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pais', '0001_initial'),
        ('lenguaje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(max_length=35)),
                ('nombre2', models.CharField(max_length=35)),
                ('apellido1', models.CharField(max_length=35)),
                ('apellido2', models.CharField(max_length=35)),
                ('edad', models.CharField(max_length=4)),
                ('ciudad', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=35)),
                ('telefono', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=20)),
                ('idlenguaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenguaje.Lenguaje')),
                ('idpais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pais.Pais')),
            ],
        ),
    ]
