<<<<<<< HEAD
# Generated by Django 2.0.5 on 2018-05-17 18:23

from django.conf import settings
=======
# Generated by Django 2.0.5 on 2018-05-17 15:32

>>>>>>> 2c134556564fbfb5e50c9cc71f2d3503aae54c65
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pais', '0001_initial'),
        ('lenguaje', '0001_initial'),
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 2c134556564fbfb5e50c9cc71f2d3503aae54c65
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(max_length=35)),
                ('nombre2', models.CharField(max_length=35)),
                ('apellido1', models.CharField(max_length=35)),
                ('apellido2', models.CharField(max_length=35)),
                ('edad', models.CharField(max_length=4)),
                ('ciudad', models.CharField(max_length=35)),
                ('telefono', models.CharField(max_length=35)),
                ('lenguaje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lenguaje.Lenguaje')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pais.Pais')),
<<<<<<< HEAD
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
>>>>>>> 2c134556564fbfb5e50c9cc71f2d3503aae54c65
            ],
        ),
    ]
