<<<<<<< HEAD
# Generated by Django 2.0.5 on 2018-05-17 18:23
=======
# Generated by Django 2.0.5 on 2018-05-17 14:53
>>>>>>> 2c134556564fbfb5e50c9cc71f2d3503aae54c65

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.CharField(max_length=35, unique=True)),
            ],
        ),
    ]
